/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SMP3KCHr8rz
 */
import Link from "next/link";

export function Landing() {
  return (
    <section className="w-full bg-gray-900 text-white py-12 md:py-24 lg:py-32">
      <div className="container grid items-center justify-center gap-4 px-4 md:px-6 lg:gap-10 m-auto">
        <div className="space-y-3 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Easy Debian Download
          </h2>
          <p className="mx-auto max-w-[700px] text-gray-300 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Choose your preferred Debian download below.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <div>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-blue-600 px-8 text-sm font-medium text-white shadow transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-blue-700 disabled:pointer-events-none disabled:opacity-50"
              href="#"
            >
              Debian 10
            </Link>
            <p className="mt-2 text-gray-300">
              Download the latest stable release of Debian, Debian 10.
            </p>
          </div>
          <div>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-green-600 px-8 text-sm font-medium text-white shadow transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-green-700 disabled:pointer-events-none disabled:opacity-50"
              href="#"
            >
              Debian 11
            </Link>
            <p className="mt-2 text-gray-300">
              Download the current testing release of Debian, Debian 11.
            </p>
          </div>
          <div>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-yellow-600 px-8 text-sm font-medium text-white shadow transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-yellow-700 disabled:pointer-events-none disabled:opacity-50"
              href="#"
            >
              Debian Testing
            </Link>
            <p className="mt-2 text-gray-300">
              Download the bleeding edge, development release of Debian.
            </p>
          </div>
          <div>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-red-600 px-8 text-sm font-medium text-white shadow transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-red-700 disabled:pointer-events-none disabled:opacity-50"
              href="#"
            >
              Debian Unstable
            </Link>
            <p className="mt-2 text-gray-300">
              Download the unstable release of Debian for the latest features.
            </p>
          </div>
        </div>
        <div className="mt-10 space-y-6 text-gray-300">
          <h3 className="text-2xl font-bold">Explanation of Debian Versions</h3>
          <p>
            <span className="text-blue-600">Debian 10:</span> The latest stable
            release of Debian, providing the robustness you need for a server
            environment.
          </p>
          <p>
            <span className="text-green-600">Debian 11:</span> The current
            testing release, suitable for users who want to help improve Debian
            by testing changes.
          </p>
          <p>
            <span className="text-yellow-600">Debian Testing:</span> The
            bleeding edge, development release, for those who want to live on
            the edge and explore the latest features.
          </p>
          <p>
            <span className="text-red-600">Debian Unstable:</span> The unstable
            release, only recommended for advanced users and developers.
          </p>
        </div>
      </div>
    </section>
  );
}
